### ISSUE TITLE
For CMAF compliance checking 'colr' box with colour_type 'nclx' should be supported

### ISSUE THREAD

**Issue by sdp198** [Dash-Industry-Forum/CMAF#16]
Content which includes a 'colr' box with colour_type 'nclx' currently produces a warning:

`WARNING: colr atom of type nclx found, the software does not handle colr atoms of this type.`

CMAF conditionally requires (in the case of an hev1 sample entry with inband parameter sets only) a colr box with nclx type.

Even if checking this isn't supported yet, it shoudn't be raised as a warning since nothing is wrong with the content being checked.

**Comment by eceozturk** [comment]
> CMAF conditionally requires (in the case of an hev1 sample entry with inband parameter sets only) a colr box with nclx type.
The related check is implemented in the software in CMAFTracksValidation.php line 152.

> WARNING: colr atom of type nclx found, the software does not handle colr atoms of this type.
This warning is  printed to let the users know that we do not do **further processing** of colr atom when the type is nclx, i.e. no other 'colr' header information is checked afterwards. But this does not affect the implemented check mentioned above.

Maybe we can change this warning to information.

**Comment by eceozturk** [comment]
Warning statement is changed to information statement. The related PR: https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/pull/432. 
Closing this issue.
