### ISSUE TITLE
Spurious errors reported for valid content where samples don't begin at the start of the mdat

### ISSUE THREAD

**Issue by sdp198** [Dash-Industry-Forum/CMAF#17]
Content for which the media samples are correctly referenced in the TrackRunBox but which don't begin at the very start of the mdat box are incorrectly reported with errors such as:

`(10 repetition\s) **'CMAF check violated: Section 7.3.2.3- All media samples in a CMAF Chunk SHALL be addressed by byte offsets in the TrackRunBox relative to first byte of the MovieFragmentBox', but not found for Rep 896x504p25 Chunk 18`

In the chunk in question here there are some bytes of private (ie not referenced from a trun) data at the start of the mdat.  It appears that the check is based on adding up the size of boxes ahead of the mdat and checking that length is what appears in the baseDataOffset.  Instead it might be better to just check that this value leads to a position within the mdat and that the total length of content in the trun doesn't, when added to this value, go beyond the end of the mdat.

**Comment by eceozturk** [comment]
This issue is addressed as suggested via PR #54. 

Closing this issue now. Please reopen if any related problems/questions appear.
