### ISSUE TITLE
update check to the CMAF IS from FDIS

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/CMAF#26]
The 'ordinality' checks for different boxes are chaned to 'cardinality'. To be changed.

"CMAF tracks shall include the following ISOBMFF boxes with nesting, optionality, and cardinality specified in the following tables, with box definitions incorporated by reference to the clauses listed in the “Specification” column that reference ISO/IEC 14496-12, ISO/IEC 23001-7, or ISO/IEC 23009-1."

**Comment by eceozturk** [comment]
Thank you for reporting this issue.
The ordinality checks have now been removed. Related PR is https://github.com/Dash-Industry-Forum/ISOSegmentValidator/pull/19
