### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/CMAF#40]

**Comment by niteeshbhat** [comment]
Integration test for Milestone 2 has been done and the report is attahced here.
[CTAWAVE_TestReport_M2_v1.xlsx.zip](https://github.com/Dash-Industry-Forum/CMAF/files/2856145/CTAWAVE_TestReport_M2_v1.xlsx.zip)

**Comment by waqarz** [comment]
Reporting provided for both MS
