### ISSUE TITLE
‘Level‘ in audio Media Profile

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/CMAF#42]
How to extract 'level' info ? Not yet clear from audio sample description entry box

![image](https://user-images.githubusercontent.com/13762418/49145372-ebb6ad00-f2ff-11e8-9f6a-0650731984f5.png)

**Comment by niteeshbhat** [comment]
In the current version of the conformance software, the conformance regarding channels is already implemented. 

Currently the info about channel is taken from the DecoderConfigDescriptor-> AudioSpecificConfig-> channelConfiguration. I hope this is what you have mentioned in your last sentence @matteo-agnelli, if i understand correctly ?

**Comment by rdoherty0** [comment]
Regarding AC-4, I found the following information internally:

The CMAF Media Profile for AC-4 is defined in Annex H of ETSI 103 190-2 v1.2.1.

CTA WAVE Media Profile for AC-4 additionally specifies that the level shall be 3.  This value corresponds to a specific AC-4 decoder that is compatible with the audio presentation.  The AC-4 decoder capability level is indicated by the mdcompat field in the ac4_presentation_v1_dsi structure.  The ac4_presentation_v1_dsi structure exists for each presentation in the ac4_dsi_v1 structure.  The ac4_dsi_v1 structure is transported in the Ac4SpecificBox (‘dac4’) of the ISOBMFF container.

**Comment by niteeshbhat** [comment]
In the current version of the conformance-software, the support for the ac4_dsi_v1_structure in 'dac4' box is not provided. We will be implementing and fixing this soon.

**Comment by hfi** [comment]
For MPEG-H Audio, profile and level are signalled by means of the `Mpegh3daProfileLevelIndication`. This indicator is part of the `MHADecoderConfigurationRecord` box (ISO/IEC 23008-3 section 20.4.) as well as MHAS packets of type `PACTYP_MPEGH3DACFG` (ISO/IEC 23008-3 section 14.4.). While the configuration record may be omitted in the ISOBMFF movie header, the MHAS packet is mandatory to be present in the movie data (mdat).

**Comment by niteeshbhat** [comment]
For Mpeg-H, Mpegh3daProfileLevelIndication field from the MHADecoderConfigurationRecord box is already validated, however there is no support for the MHAS packet in the bitstream /mdat box ,in the current version of the software. Fraunhofer IIS and Nomor will take this issue (regarding Mpeg-H) offline to discuss the technical details of required bitstream validation.

**Comment by niteeshbhat** [comment]
The ac-4 level check updated as per the above discussions (using ac4_dsi_v1 structures from ETSI 103 190-2 v1.2.1) - https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/pull/437

**Comment by niteeshbhat** [comment]
The remaining issue of bitstream validation support in the Conformance-Software is opened here
https://github.com/Dash-Industry-Forum/CMAF/issues/48
