### ISSUE TITLE
Dynamic range and color space for Splice Constraints

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/CMAF#45]
For the conformance of Splice constraints, there is a SHOULD condition in the Table 6 of WAVE Content Spec as additional recommended Splice Constraints for continuity of user experience.

"Video Dynamic range and color space- SHOULD be consistent between Related Video Switching Sets for consistent user experience on render and display systems with limited tone mapping capabilities"

The implementation of this check is not yet clear.
What does color space here mean -is it the 'color_primaries, transfer_characteristics, matrix_coeff' found in the SPS VUI ?? (these are already checked for video media profile !!)
Also 'dynamic range' parameter for video is not found in SPS. Where to find it ?

Any comments on this conformance check?

**Comment by waqarz** [comment]
By implementing "Sequential Switching Sets SHALL conform to the _same_ CMAF Media Profile" in https://github.com/Dash-Industry-Forum/CMAF/issues/35, this is already implemented: same CMAF Media Profile, among other things, mandate _same_ Color primaries, matrix coefficients, and Transfer Characteristics.
